// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA2dy-2vq0_I-oVrfLC4OgvjKSKCCTpWw',
    appId: '1:1009379504211:web:5f68a871988f90abd2d6a6',
    messagingSenderId: '1009379504211',
    projectId: 'akrili-e4f98',
    authDomain: 'akrili-e4f98.firebaseapp.com',
    storageBucket: 'akrili-e4f98.firebasestorage.app',
    measurementId: 'G-H3L3JL8G5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYGIvrPR9Q3kzc7_s2qCBD1o2G3H_B7kk',
    appId: '1:1009379504211:android:3adb063e76de541fd2d6a6',
    messagingSenderId: '1009379504211',
    projectId: 'akrili-e4f98',
    storageBucket: 'akrili-e4f98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtCrLU7g5wTmF9qxJOcPXSiWCptSgCi68',
    appId: '1:1009379504211:ios:b02c9c2d94bb265fd2d6a6',
    messagingSenderId: '1009379504211',
    projectId: 'akrili-e4f98',
    storageBucket: 'akrili-e4f98.firebasestorage.app',
    iosBundleId: 'com.example.aairbnb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtCrLU7g5wTmF9qxJOcPXSiWCptSgCi68',
    appId: '1:1009379504211:ios:b02c9c2d94bb265fd2d6a6',
    messagingSenderId: '1009379504211',
    projectId: 'akrili-e4f98',
    storageBucket: 'akrili-e4f98.firebasestorage.app',
    iosBundleId: 'com.example.aairbnb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA2dy-2vq0_I-oVrfLC4OgvjKSKCCTpWw',
    appId: '1:1009379504211:web:f0e2e29bcca5c624d2d6a6',
    messagingSenderId: '1009379504211',
    projectId: 'akrili-e4f98',
    authDomain: 'akrili-e4f98.firebaseapp.com',
    storageBucket: 'akrili-e4f98.firebasestorage.app',
    measurementId: 'G-P9M0MBN4G9',
  );
}
