name: aairbnb
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets\images\logo.png
    - assets/images/discover.png
    - assets/images/authentically.png
    - assets/images/hospitality.png
    - assets/images/logo for main.png
    - assets/images/courtyard.png

  fonts:
    - family: CormorantGaramond
      fonts:
        - asset: assets/fonts/CormorantGaramond-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/CormorantGaramond-VariableFont_wght.ttf
          weight: 700
    - family: HankenGrotesk
      fonts:
        - asset: assets/fonts/HankenGrotesk-VariableFont_wght.ttf
        - asset: assets/fonts/HankenGrotesk-Italic-VariableFont_wght.ttf
          style: italic      